package localizer

const (
	SendVerifiedCodeSubject  = "SendVerifiedCodeSubject"
	SendVerifiedCodeBody     = "SendVerifiedCodeBody"
	FieldRequired            = "FieldRequired"
	FieldEmail               = "FieldEmail"
	FieldMin                 = "FieldMin"
	FieldDefault             = "FieldDefault"
	InvalidEmailCode         = "InvalidEmailCode"
	ExpiredEmailCode         = "ExpiredEmailCode"
	InvalidBody              = "InvalidBody"
	AccountIsBlocked         = "AccountIsBlocked"
	AccountBanForever        = "AccountBanForever"
	EmailConfirm             = "EmailConfirm"
	Forbidden                = "Forbidden"
	UserNotFoundByEmail      = "UserNotFoundByEmail"
	ResetPasswordEmail       = "ResetPasswordEmail"
	ResetPasswordSubject     = "ResetPasswordSubject"
	InvalidResetPasswordCode = "InvalidResetPasswordCode"
	CodeExpired              = "CodeExpired"
	LastPasswords            = "LastPasswords"
	Unauthorized             = "Unauthorized"
	UserIsExists             = "UserIsExists"
	InvalidEmailOrPassword   = "InvalidEmailOrPassword"
	UserIsBlocked            = "UserIsBlocked"
)
